apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-ecr-repo
  labels:
    app: dev-ecr-repo
    tier: frontend
  namespace: devtest
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      app: dev-ecr-repo

  template:
    metadata:
      labels:
        app: dev-ecr-repo
    spec:
     containers:
      - name: dev-ecr-repo
        image: 217903889262.dkr.ecr.eu-west-2.amazonaws.com/dev-ecr-repo:latest
        ports:
        - containerPort: 3000
        # resources:
        #       requests:
        #         cpu: 100m
        #         memory: 512Mi
        #       limits:
        #         cpu: 200m 
        #         memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: dev-ecr-repo-svc
  namespace: devtest
  labels:
    app: dev-ecr-repo
spec:
  type: LoadBalancer
  selector:
    app: dev-ecr-repo
  ports:
    - port: 3000
      targetPort: 3000

---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: customer-sl-ing
#   namespace: prod-env
# spec:
#   ingressClassName: kong
#   rules:
#   - host:  gateway.meterservicehub.com
#   - http:
#       paths:
#       - backend:
#           service:
#             name: dev-ecr-repo-sl-svc
#             port:
#               number: 9001
#         path: /customer
#         pathType: Prefix
