import React from "react";
import { Link } from "react-router-dom";
import { FaCaretRight } from "react-icons/fa";

import PublicGenericLayout from "../../../components/GenericLayout/PublicGenericLayout";
import MeetingInput from "../../../components/MeetingInput/MeetingInput";
import CustomInput from "../../../components/FormFields/Input/Input";

import style from "./Report.module.scss";
import "./Report.scss";

const Report = () => {
  return (
    <PublicGenericLayout>
      <section className={style.report_container}>
        <div className={style.report_wrapper}>
          <div className={style.blur_block_green}></div>
          <button className={style.report_download_btn}>Download Report</button>
          <div className={style.report_download_title}>
            Enter Meeting Link to Download Report
          </div>
          <div className={style.report_download_summary}>
            Enter the meeting code to download the report and recording specific
            to your meeting. Only report and recording generated by host can be
            retrieved.
          </div>
          <MeetingInput customStyle={[style.download_meeting_wrapper]}>
            <CustomInput
              placeHolder="Enter meeting code"
              onChange={() => {}}
              customStyle={[style.download_meeting]}
            />
            <button className={style.meeting__btn}>
              <span className={style.meeting__btn__text}>Download Report</span>
            </button>
          </MeetingInput>
          <div className={style.blur_block_red}></div>
          <div className={style.searh_event_para}>
            Or{" "}
            <Link to="/events" className={style.search_event_link}>
              Search for Event{" "}
            </Link>{" "}
            <span className={style.search_event_subtext}>
              {"if you can't remember the meeting code"}
            </span>
            <Link to="/events" className={style.horizontal_block_box}>
              <span className={style.horizontal_block}></span>
              <FaCaretRight color="red" size="13" />
            </Link>
          </div>
        </div>
      </section>
    </PublicGenericLayout>
  );
};

export default Report;
